#*******************************************************************************
#
#      $Log: Makefile.msc,v $
#      Revision 1.3  2009/05/01 15:08:33  fisa
#      do not compile!
#
#      Revision 1.2  2008/11/27 15:47:13  lzabeo
#      *** empty log message ***
#
#      Revision 1.1  2008/08/27 16:32:14  fisa
#      *** empty log message ***
#
#*******************************************************************************/

TARGET=msc

all:

clean:
